with new_values as
(
SELECT
  PUBLIC.hash8(t.game_id||'|'||t.team_id)::BIGINT fct_game_team_guid,
  (t.game_id||'|'||t.team_id)::VARCHAR crc_str,
  dg.dim_game_guid::BIGINT,
  t.game_id::VARCHAR,
  t.matchup::VARCHAR,
  dt.dim_team_guid::BIGINT, 
  t.team_id,
  t.team_abbreviation team_abbrv,
  lnd.get_loc_from_matchup(t.team_abbreviation, t.matchup) team_loc,
  dot.dim_team_guid::BIGINT dim_opp_team_guid, 
  rt.team_id opp_team_id,
  rt.team_abbreviation opp_team_abbrv,
  t.game_date,
  public.hash8(replace(t.season,'-','')::integer) dim_season_guid,
  replace(t.season,'-','')::integer season,
  CASE 
    WHEN t.season_type = 'Regular+Season' THEN 'RS'
    WHEN t.season_type = 'Playoffs' THEN 'PO'
    WHEN t.season_type = 'Pre+Season' THEN 'PS'
    ELSE 'U'
  END::VARCHAR season_type,  
  t.wl,
  t.MIN minutes,
  t.fgm 		   fgm, 		
  t.fga        fga, 
  t.fg_pct     fg_pct, 
  t.fg3m       fg3m, 
  t.fg3a       fg3a, 
  t.fg3_pct    fg3_pct, 
  t.ftm        ftm, 
  t.fta        fta, 
  t.ft_pct     ft_pct, 
  t.oreb       oreb, 
  t.dreb       dreb, 
  t.reb        reb, 
  t.ast        ast, 
  t.stl        stl, 
  t.blk        blk, 
  t.tov        tov, 
  t.pf         pf, 
  t.pts        pts, 
  t.plus_minus plus_minus,
  ta.off_rating  off_rating,
  ta.def_rating  def_rating,
  ta.net_rating  net_rating,
  ta.ast_pct     ast_pct,
  ta.ast_tov     ast_tov,
  ta.ast_ratio   ast_ratio,
  ta.oreb_pct    oreb_pct,
  ta.dreb_pct    dreb_pct,
  ta.reb_pct     reb_pct,
--  ta.tm_tov_pct  tm_tov_pct,
  ta.efg_pct     efg_pct,
  ta.ts_pct      ts_pct,
  ta.usg_pct     usg_pct,
  ta.pace        pace,
  ta.pie         pie,  
  tm.pts_off_tov          pts_off_tov,
  tm.pts_2nd_chance       pts_2nd_chance,
  tm.pts_fb               pts_fb,
  tm.pts_paint            pts_paint,
  tm.opp_pts_off_tov      opp_pts_off_tov,
  tm.opp_pts_2nd_chance   opp_pts_2nd_chance,
  tm.opp_pts_fb           opp_pts_fb,
  tm.opp_pts_paint        opp_pts_paint,
  tm.blka                 blka,
  tm.pfd                  pfd,  
--  tff.efg_pct       efg_pct,
  tff.fta_rate      fta_rate,
  tff.tm_tov_pct    tm_tov_pct,
  tff.opp_efg_pct   opp_efg_pct,
  tff.opp_fta_rate  opp_fta_rate,
  tff.opp_tov_pct   opp_tov_pct,
  tff.opp_oreb_pct  opp_oreb_pct,    
  tsc.pct_fga_2pt       pct_fga_2pt,
  tsc.pct_fga_3pt       pct_fga_3pt,
  tsc.pct_pts_2pt       pct_pts_2pt,
  tsc.pct_pts_2pt_mr    pct_pts_2pt_mr,
  tsc.pct_pts_3pt       pct_pts_3pt,
  tsc.pct_pts_fb        pct_pts_fb,
  tsc.pct_pts_ft        pct_pts_ft,
  tsc.pct_pts_off_tov   pct_pts_off_tov,
  tsc.pct_pts_paint     pct_pts_paint,
  tsc.pct_ast_2pm       pct_ast_2pm,
  tsc.pct_uast_2pm      pct_uast_2pm,
  tsc.pct_ast_3pm       pct_ast_3pm,
  tsc.pct_uast_3pm      pct_uast_3pm,
  tsc.pct_ast_fgm       pct_ast_fgm,
  tsc.pct_uast_fgm      pct_uast_fgm,  
  trck.dist     dist,
  trck.orbc     orbc,
  trck.drbc     drbc,
  trck.rbc      rbc,
  trck.tchs     tchs,
  trck.sast     sast,
  trck.ftast    ftast,
  trck.pass     pass,
  trck.cfgm     cfgm,
  trck.cfga     cfga,
  trck.cfg_pct  cfg_pct,
  trck.ufgm     ufgm,
  trck.ufga     ufga,
  trck.ufg_pct  ufg_pct,
  trck.dfgm     dfgm,
  trck.dfga     dfga,
  trck.dfg_pct  dfg_pct,
  now() created_at,
  now() updated_at,
  true is_active
  
FROM lnd.vw_games t
	INNER JOIN lnd.vw_games rt ON ( t.game_id = rt.game_id and
					rt.team_id != t.team_id)

	left outer JOIN rpt.dim_game dg ON ( t.game_id = dg.ID )
	left outer JOIN rpt.dim_team dt ON ( t.team_id = dt.ID ) 
	left outer JOIN rpt.dim_team dot ON ( rt.team_id = dot.ID ) 
	left outer JOIN lnd.vw_game_team_adv_stat ta ON (ta.game_id = t.game_id AND
												ta.team_id = t.team_id )
	left outer JOIN lnd.vw_game_team_misc_stat tm ON ( tm.game_id = t.game_id AND
												  tm.team_id = t.team_id )
	left outer JOIN lnd.vw_game_team_four_factor_stat tff ON ( tff.game_id = t.game_id AND
														  tff.team_id = t.team_id )
	left outer JOIN lnd.vw_game_team_scoring_stat tsc ON ( tsc.game_id = t.game_id AND
													  tsc.team_id = t.team_id )                          
	left outer JOIN lnd.vw_game_team_trck_stat trck ON ( trck.game_id = t.game_id AND
													trck.team_id = t.team_id )                                                        
),
upsert as
(
UPDATE rpt.fct_game_team gt
   SET 
	crc_str = nv.crc_str,
	dim_game_guid = nv.dim_game_guid,
	game_id = nv.game_id,
	matchup = nv.matchup,
	dim_team_guid = nv.dim_team_guid,
	team_id = nv.team_id,
	team_abbrv = nv.team_abbrv,
	team_loc = nv.team_loc,
	dim_opp_team_guid = nv.dim_opp_team_guid,
	opp_team_id = nv.opp_team_id,
	opp_team_abbrv = nv.opp_team_abbrv,
	game_date = nv.game_date,
	dim_season_guid = nv.dim_season_guid,
	season = nv.season,
	season_type = nv.season_type,
	wl = nv.wl,
	minutes = nv.minutes,
	fgm = nv.fgm,
	fga = nv.fga,
	fg_pct = nv.fg_pct,
	fg3m = nv.fg3m,
	fg3a = nv.fg3a,
	fg3_pct = nv.fg3_pct,
	ftm = nv.ftm,
	fta = nv.fta,
	ft_pct = nv.ft_pct,
	oreb = nv.oreb,
	dreb = nv.dreb,
	reb = nv.reb,
	ast = nv.ast,
	stl = nv.stl,
	blk = nv.blk,
	tov = nv.tov,
	pf = nv.pf,
	pts = nv.pts,
	plus_minus = nv.plus_minus,
	off_rating = nv.off_rating,
	def_rating = nv.def_rating,
	net_rating = nv.net_rating,
	ast_pct = nv.ast_pct,
	ast_tov = nv.ast_tov,
	ast_ratio = nv.ast_ratio,
	oreb_pct = nv.oreb_pct,
	dreb_pct = nv.dreb_pct,
	reb_pct = nv.reb_pct,
	efg_pct = nv.efg_pct,
	ts_pct = nv.ts_pct,
	usg_pct = nv.usg_pct,
	pace = nv.pace,
	pie = nv.pie,
	pts_off_tov = nv.pts_off_tov,
	pts_2nd_chance = nv.pts_2nd_chance,
	pts_fb = nv.pts_fb,
	pts_paint = nv.pts_paint,
	opp_pts_off_tov = nv.opp_pts_off_tov,
	opp_pts_2nd_chance = nv.opp_pts_2nd_chance,
	opp_pts_fb = nv.opp_pts_fb,
	opp_pts_paint = nv.opp_pts_paint,
	blka = nv.blka,
	pfd = nv.pfd,
	fta_rate = nv.fta_rate,
	tm_tov_pct = nv.tm_tov_pct,
	opp_efg_pct = nv.opp_efg_pct,
	opp_fta_rate = nv.opp_fta_rate,
	opp_tov_pct = nv.opp_tov_pct,
	opp_oreb_pct = nv.opp_oreb_pct,
	pct_fga_2pt = nv.pct_fga_2pt,
	pct_fga_3pt = nv.pct_fga_3pt,
	pct_pts_2pt = nv.pct_pts_2pt,
	pct_pts_2pt_mr = nv.pct_pts_2pt_mr,
	pct_pts_3pt = nv.pct_pts_3pt,
	pct_pts_fb = nv.pct_pts_fb,
	pct_pts_ft = nv.pct_pts_ft,
	pct_pts_off_tov = nv.pct_pts_off_tov,
	pct_pts_paint = nv.pct_pts_paint,
	pct_ast_2pm = nv.pct_ast_2pm,
	pct_uast_2pm = nv.pct_uast_2pm,
	pct_ast_3pm = nv.pct_ast_3pm,
	pct_uast_3pm = nv.pct_uast_3pm,
	pct_ast_fgm = nv.pct_ast_fgm,
	pct_uast_fgm = nv.pct_uast_fgm,
	dist = nv.dist,
	orbc = nv.orbc,
	drbc = nv.drbc,
	rbc = nv.rbc,
	tchs = nv.tchs,
	sast = nv.sast,
	ftast = nv.ftast,
	pass = nv.pass,
	cfgm = nv.cfgm,
	cfga = nv.cfga,
	cfg_pct = nv.cfg_pct,
	ufgm = nv.ufgm,
	ufga = nv.ufga,
	ufg_pct = nv.ufg_pct,
	dfgm = nv.dfgm,
	dfga = nv.dfga,
	dfg_pct = nv.dfg_pct,
	updated_at=now(), 
	is_active=true
from new_values nv
where gt.fct_game_team_guid = nv.fct_game_team_guid
returning gt.*	
)
INSERT INTO rpt.fct_game_team(
            fct_game_team_guid, crc_str, dim_game_guid, game_id, matchup, 
            dim_team_guid, team_id, team_abbrv, team_loc, dim_opp_team_guid, opp_team_id, opp_team_abbrv, 
            game_date, dim_season_guid, season, season_type, wl, minutes, 
            fgm, fga, fg_pct, fg3m, fg3a, fg3_pct, ftm, fta, ft_pct, oreb, 
            dreb, reb, ast, stl, blk, tov, pf, pts, plus_minus, off_rating, 
            def_rating, net_rating, ast_pct, ast_tov, ast_ratio, oreb_pct, 
            dreb_pct, reb_pct, efg_pct, ts_pct, usg_pct, pace, pie, pts_off_tov, 
            pts_2nd_chance, pts_fb, pts_paint, opp_pts_off_tov, opp_pts_2nd_chance, 
            opp_pts_fb, opp_pts_paint, blka, pfd, fta_rate, tm_tov_pct, opp_efg_pct, 
            opp_fta_rate, opp_tov_pct, opp_oreb_pct, pct_fga_2pt, pct_fga_3pt, 
            pct_pts_2pt, pct_pts_2pt_mr, pct_pts_3pt, pct_pts_fb, pct_pts_ft, 
            pct_pts_off_tov, pct_pts_paint, pct_ast_2pm, pct_uast_2pm, pct_ast_3pm, 
            pct_uast_3pm, pct_ast_fgm, pct_uast_fgm, dist, orbc, drbc, rbc, 
            tchs, sast, ftast, pass, cfgm, cfga, cfg_pct, ufgm, ufga, ufg_pct, 
            dfgm, dfga, dfg_pct, created_at, updated_at, is_active)
SELECT fct_game_team_guid, crc_str, dim_game_guid, game_id, matchup, 
       dim_team_guid, team_id, team_abbrv, team_loc, dim_opp_team_guid, opp_team_id, opp_team_abbrv, 
       game_date, dim_season_guid, season, season_type, wl, minutes, 
       fgm, fga, fg_pct, fg3m, fg3a, fg3_pct, ftm, fta, ft_pct, oreb, 
       dreb, reb, ast, stl, blk, tov, pf, pts, plus_minus, off_rating, 
       def_rating, net_rating, ast_pct, ast_tov, ast_ratio, oreb_pct, 
       dreb_pct, reb_pct, efg_pct, ts_pct, usg_pct, pace, pie, pts_off_tov, 
       pts_2nd_chance, pts_fb, pts_paint, opp_pts_off_tov, opp_pts_2nd_chance, 
       opp_pts_fb, opp_pts_paint, blka, pfd, fta_rate, tm_tov_pct, opp_efg_pct, 
       opp_fta_rate, opp_tov_pct, opp_oreb_pct, pct_fga_2pt, pct_fga_3pt, 
       pct_pts_2pt, pct_pts_2pt_mr, pct_pts_3pt, pct_pts_fb, pct_pts_ft, 
       pct_pts_off_tov, pct_pts_paint, pct_ast_2pm, pct_uast_2pm, pct_ast_3pm, 
       pct_uast_3pm, pct_ast_fgm, pct_uast_fgm, dist, orbc, drbc, rbc, 
       tchs, sast, ftast, pass, cfgm, cfga, cfg_pct, ufgm, ufga, ufg_pct, 
       dfgm, dfga, dfg_pct, now(), NULL, true
  FROM new_values
 where not exists ( select 1 
					  from upsert up
					 where up.fct_game_team_guid = new_values.fct_game_team_guid )
;				 